### ISSUE TITLE
CDNSP uses?

### ISSUE THREAD

**Issue by 877dev** [Bob123a1/CDNSP-GUI-Files#7]
Hi @Bob123a1 

I'm a bit out of the loop, but I noticed you made new commits recently.

Is CDNSP still useful for managing nsp archives? Or any other uses?

Many thanks! :)

**Comment by Bob123a1** [comment]
It is still a great tool for managing which NSP is out of date as well as finding game information and pictures

**Comment by 877dev** [comment]
@Bob123a1 yes it sure is. Thanks :)
